version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: plena-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plena-studio
      MYSQL_USER: plena_user
      MYSQL_PASSWORD: plena_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d
    networks:
      - plena-network

  # Backend API en modo desarrollo
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: plena-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=plena_user
      - DB_PASSWORD=plena_password
      - DB_NAME=plena-studio
      - JWT_SECRET=dev-jwt-secret-key
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - plena-network
    volumes:
      - ./Backend/src:/app/src
    command: npm run start:dev

volumes:
  mysql_dev_data:

networks:
  plena-network:
    driver: bridge
